version: 2
jobs:
  build:
    docker:
      - image: rsridivya/terraform
    steps:
      - checkout
      - run:
          name: Check Terraform Version
          command: terraform -v
      - run:
          name: Check AWSCLI Version
          command: aws --version
      - run:
          name: Init terraform
          command: terraform init
      - run:
          name: Configure S3->Terraform
          command: terraform remote config -backend=S3 -backend-config="terraform-state-saver" -backend-config="key=/terraform.tfstate" -backend-config="region=us-east-1"
